#!/bin/sh /etc/rc.common

START=98
STOP=20
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/sbin/sms-to-telegram run
	procd_set_param respawn 3600 5 5
	procd_set_param term_timeout 10
	procd_close_instance
}
